# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-05 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0058_processrun_rto'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='config',
            field=models.TextField(blank=True, null=True, verbose_name='XML格式存放系统/数据库预置信息'),
        ),
    ]
