# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-09 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0059_process_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='backup_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.HostsManage', verbose_name='备机'),
        ),
    ]
