# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-12 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0060_process_backup_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='backup_host',
        ),
        migrations.AlterField(
            model_name='process',
            name='config',
            field=models.TextField(blank=True, null=True, verbose_name='XML格式存放预案变量/系统数据库信息/恢复变量/主机变量'),
        ),
    ]
