# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-12 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0061_auto_20191212_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrun',
            name='config',
            field=models.TextField(blank=True, null=True, verbose_name='恢复变量/主机变量'),
        ),
        migrations.AlterField(
            model_name='process',
            name='config',
            field=models.TextField(blank=True, null=True, verbose_name='XML格式存放预案变量/系统数据库信息'),
        ),
    ]
