# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-17 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0062_auto_20191212_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostsmanage',
            name='config',
            field=models.TextField(blank=True, null=True, verbose_name='主机相关配置'),
        ),
        migrations.AddField(
            model_name='hostsmanage',
            name='host_type',
            field=models.IntegerField(blank=True, choices=[(1, 'NBU源机'), (2, 'NBU备机'), (3, 'Oracle源机'), (4, 'Oracle备机')], null=True, verbose_name='主机类型'),
        ),
    ]
